# .pre-commit-config.yaml

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: docformatter
        name: docformatter
        entry: docformatter
        language: python
        types: [python]
        additional_dependencies: [docformatter==1.7.5]
        args:
          - --black
          - --style=numpy
          - --blank
          - --in-place

  - repo: https://github.com/psf/black
    rev: 23.9.1  # Use the latest stable version
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0  # Use the latest stable version
    hooks:
      - id: flake8
        args: [
          --max-line-length=88,
          '--ignore=D205,D400,D105,E731,W503,D401,E203,D209,E741'
        ]
        additional_dependencies: [flake8-docstrings]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        args:
          - --ignore-missing-imports
          - --exclude=artlib/cvi/
          - --follow-imports=silent

exclude: ^(unit_tests/|scripts/|artlib/experimental/|examples/|docs/|artlib/cvi
  /|setup.py|torch_optimized/)
