[project]
name = "artlib"
version = "0.1.3"
description = "A Python library for Adaptive Resonance Theory (ART) algorithms."
authors = [{ name = "Niklas M. Melton", email = "niklasmelton@gmail.com" }]
license = { text = "MIT" }
readme = "README.md"

dependencies = [
    "numpy>=1.19.4",
    "scipy>=1.5.4",
    "scikit-learn>=1.0",
    "matplotlib>=3.3.3",
    "numba>=0.57.0"
]

[tool.poetry]
name = "artlib"
version = "0.1.3"
description = "A Python library for Adaptive Resonance Theory (ART) algorithms."
authors = ["Niklas M. Melton <niklasmelton@gmail.com>"]
license = "MIT"
homepage = "https://github.com/NiklasMelton/AdaptiveResonanceLib"
repository = "https://github.com/NiklasMelton/AdaptiveResonanceLib"
documentation = "https://github.com/NiklasMelton/AdaptiveResonanceLib"
readme = "README.md"
build = "build_extension.py"

[tool.setuptools.packages.find]
include = ["artlib*"]
exclude = ["data*", "figures*", "templates*"]

[tool.poetry.dependencies]
python = "^3.9"
numpy = ">=1.19.4"
scipy = ">=1.5.4"
scikit-learn = ">=1.0"
matplotlib = ">=3.3.3"
numba = ">=0.57.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.2"
pre-commit = "^4.0.0"

[tool.poetry.group.docs.dependencies]
sphinx = "^6.2.1"
sphinx-rtd-theme = "^1.0.0"
sphinx-autoapi = ">=3.0.0"
myst-parser = "^1.0"
cffconvert = "^2.0.0"
sphinxcontrib-bibtex = "^2.0.0"

# Specify build system for C++ extensions
[build-system]
requires = ["poetry-core>=1.0.0", "setuptools", "pybind11"]
build-backend = "poetry.core.masonry.api"
