name: Run Python Unit Tests

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install --with dev  # Install dependencies from pyproject.toml, including dev dependencies

    - name: Run tests
      run: |
        poetry run pytest unit_tests/ --maxfail=5 --disable-warnings -v --tb=short  # Add verbose and short traceback options

    - name: Publish test results
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: pytest-results
        path: ./test-results/pytest-report.xml
