name: Run Python Unit Tests

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install --with dev --no-root

    - name: Build wheel
      run: |
        poetry build
        ls -l dist  # show the generated wheel

    - name: Install wheel
      run: |
        pip install dist/*.whl
        # Now the compiled extension is in site-packages

    - name: Show installed 'artlib'
      run: |
        poetry run pip show -f artlib
        poetry run python -c "import sys; print(sys.path)"

    - name: Debug Poetry Package Contents
      run: |
        tar -tf dist/*.tar.gz | grep cpp_optimized || echo "No C++ files found!"

    - name: Run tests
      run: |
        poetry run pytest unit_tests/ --maxfail=5 --disable-warnings -v --tb=short --junitxml=./test-results/pytest-report.xml  # Ensure JUnit XML report is generated

    - name: Publish test results
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: pytest-results
        path: ./test-results/pytest-report.xml
        compression-level: 6  # Optional: Adjusts compression for artifact storage efficiency
