name: Run Python Unit Tests

on:
  pull_request:
    branches:
      - main
      - master  # Adjust based on your main branch name

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Specify the Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry  # If you're using Poetry
        poetry install  # Install dependencies from pyproject.toml

    - name: Run tests
      run: |
        pytest unit_tests/ --maxfail=5 --disable-warnings  # Run tests from unit_tests/ directory

    - name: Publish test results
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: pytest-results
        path: ./test-results/pytest-report.xml
